#ifndef __MACROS__
#define __MACROS__

#define TAM_CHAVE 3
#define TAM_NUMERO_DDD 2
#define TAM_NUMERO_PREFIXO 5
#define TAM_NUMERO_SUFIXO 4
#define TAM_NUMERO TAM_NUMERO_DDD+TAM_NUMERO_PREFIXO+TAM_NUMERO_SUFIXO
#define TAM_DATA_DIA 2
#define TAM_DATA_MES 2
#define TAM_DATA_ANO 4
#define TAM_DATA TAM_DATA_DIA+TAM_DATA_MES+TAM_DATA_ANO
#define TAM_EMAIL 30
#define TAM_NOME 48

#define FILE_NAME "arquivo.bin"
#define INDICE_FILE_NAME "indice.bin"

#define TAM_BLOCK 512
#define TAM_CABECALHO 50

#define TAM_REGISTRO 100
#define QTD_REG_1O_BLOCO (TAM_BLOCK - TAM_CABECALHO) / TAM_REGISTRO
#define QTD_REG_P_BLOCO TAM_BLOCK / TAM_REGISTRO

#define TAM_INDICE (TAM_CHAVE+8)
#define QTD_IND_1O_BLOCO (TAM_BLOCK - TAM_CABECALHO) / TAM_INDICE
#define QTD_IND_P_BLOCO TAM_BLOCK / TAM_INDICE

#define RRN2NBLOCK(rrn) (rrn / TAM_BLOCK)
#define RRN2REGINBLOCK(rrn) (rrn - RRN2NBLOCK(rrn) * TAM_BLOCK)

#endif